### ISSUE TITLE
CCAPI documentation?

### ISSUE THREAD

**Issue by shealan** [camerahacks/canon-ccapi-node#1]
I'd love to take this concept further but can't find any documentation for the CCAPI anywhere. The SDK download contains information about the traditional software API but not the new CCAPI REST endpoints. As usual the Canon website useless.

Any idea where I could find this?

**Comment by fundix** [comment]
I have doc from Canon.

Eg: GET http://192.168.1.2:8080/ccapi
You get all supported commands from camera

**Comment by camerahacks** [comment]
If you go to my website, you can find information on how to register and download the CCAPI manual.
https://dphacks.com/how-to-canon-camera-control-api-ccapi/

**Comment by ekatzenstein** [comment]
@shealan this is the best I could find. I don't know anything about the dev but it's been helpful: https://github.com/horshack-dpreview/Canomate/blob/master/canomate.py
